// Regenerates src/components/wordmark-data.ts from brand/wordmark.svg, the
// single source of the wordmark. Run after editing the SVG: npm run brand:sync
import { readFileSync, writeFileSync } from "node:fs";

const svg = readFileSync(new URL("../brand/wordmark.svg", import.meta.url), "utf8");
const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
const paths = Array.from(svg.matchAll(/<path d="([^"]+)"/g), (m) => m[1]);
if (!viewBox || paths.length === 0) {
  throw new Error("brand/wordmark.svg: no viewBox or no <path d> found");
}

const out = `// GENERATED by scripts/sync-wordmark.ts from brand/wordmark.svg. Do not edit.
export const WORDMARK_VIEWBOX = ${JSON.stringify(viewBox)};
export const WORDMARK_PATHS: readonly string[] = ${JSON.stringify(paths)};
`;
writeFileSync(new URL("../src/components/wordmark-data.ts", import.meta.url), out);
console.log(`wordmark-data.ts written: viewBox ${viewBox}, ${paths.length} paths`);
